### ISSUE TITLE
s390x related fixes for tekton pipeline

### ISSUE THREAD

**Issue by barthy1** [tektoncd/pipeline#3064]
At this moment tekton pipeline is tested and released only for amd64 architecture.
I'd like to use this issue to track issues/work to run and test tekton pipeline on s390x architecture (IBM Z).
This work is part of https://github.com/tektoncd/plumbing/issues/495 discussion.
List of issues/PRs can be updated in the future.

Bugs in the code:

- [x]  fail to run task with multi-arch image on non amd64 cluster ([issue](https://github.com/tektoncd/pipeline/issues/3086), [PR](https://github.com/tektoncd/pipeline/pull/3337)) 

e2e test errors:
- amd64 only test images (fails to run on s390x):
  - [x] alpine/git (merged [PR](https://github.com/alpine-docker/git/pull/23))
  - [ ] alpine/helm
  - [ ] gcr.io/kaniko-project/executor (merged [PR](https://github.com/GoogleContainerTools/kaniko/pull/1475))
  - [ ] gcr.io/tekton-releases/dogfooding/skopeo ([PR](https://github.com/tektoncd/plumbing/pull/629))
  - [ ] quay.io/rhpipeline/skopeo:alpine ([issue](https://github.com/containers/skopeo/issues/1010), [PR](https://github.com/containers/skopeo/pull/1066))
- [x] sha for busybox is amd64 specific for TestTaskRunStatus test -> https://github.com/tektoncd/pipeline/pull/3061

examples test errors:
- amd64 only test images (fails to run on s390x):
  - [ ] quay.io/rhpipeline/skopeo:alpine ([issue](https://github.com/containers/skopeo/issues/1010), [PR](https://github.com/containers/skopeo/pull/1066))
  - [x] gcr.io/cloud-builders/git (merged [PR](https://github.com/tektoncd/pipeline/pull/3372))
  - [ ] gcr.io/kaniko-project/executor:v0.17.1 ([PR](https://github.com/GoogleContainerTools/kaniko/pull/1475))
  - [x] registry  (replaced by available image for s390x) (merged [PR](https://github.com/tektoncd/pipeline/pull/3107))
  - [x] gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.11.0
  - [ ] docker:dind
  - [ ] docker
  - [x] alpine/git:v2.24.3 (merged [PR](https://github.com/tektoncd/pipeline/pull/3372))
  - gcr.io/tekton-releases/dogfooding/alpine-git-nonroot:mario ([PR](https://github.com/tektoncd/plumbing/pull/629))
  - [x] node (merged [PR](https://github.com/tektoncd/pipeline/pull/3372))

PR https://github.com/tektoncd/pipeline/pull/3107 to temporarily exclude failing tests is done

**Comment by pritidesai** [comment]
@barthy1 how about the [examples](https://github.com/tektoncd/pipeline/tree/master/examples)? any changes needed in sample `YAML`s?

**Comment by barthy1** [comment]
@pritidesai yeah, examples are actually in worse state for non Intel architectures :(
I am working now to identify at least most common reasons of the failures. Most of the errors are still connected to test images, available only for amd64. So soon the issue will be extended with examples section
