### ISSUE TITLE
Towards v1 API

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/pipeline#3548]
*This issue is here to track work towards the `v1` API of `tektoncd/pipeline`. It is loosely based on the [initial doc](https://docs.google.com/document/d/1h9n0Lod0OiJ_sP2HK8Ms7N04aee5LW8xfz5yMGCFMIs/edit) around this, and will be update as we go.*

## Motivation

In order to declare Pipeline stable and ready to use in *production*
to our users and customer, we need to give them some
guarantees. Although `v1beta1` has some guarantees, most users are
waiting for a `v1` API set that they can rely on for the long term.

If we can, in addition, come with a set of *rules* that would help us
decide when a feature request should be considered as required or not
for a `v1` API, this would be nice 🙃.

## Identified work

- [ ] API versions and new features #3459 @vdemeester @skaegi @afrittoli 
- [x] Better credential UX #2343 @sbwsg 
  - [ ] Consider projected volumes #3551 (in relation to credential UX @sbwsg) — timebox work on investigation
- [ ] Additionnal workspace support (@sbwsg tracking issue to be created on workspaces)
- [ ] PipelineResource future #1673 @jerop @sbwsg @vdemeester 
  - [Tekton PipelineResources Beta Roadmap](https://docs.google.com/document/d/1RYP61CA-M5GW7zp4GYbMD99r1d188Ts8tzO68FPBIvQ/edit?ts=5fb81289#heading=h.y5ki9rp0u9yi)
- [ ] Resources Limit/Request & LimitRange support #2986 @vdemeester
- [x] Failure strategies #3345 #2800 @jerop (if there is anything else to add)
- [x] [Custom tasks](https://github.com/tektoncd/community/blob/master/teps/0002-custom-tasks.md) #3133 #3463 @ImJasonH @GregDritschler 
- [ ] Migration path from `v1beta1` to `v1` @vdemeester 
  - Documentation
  - Conversion webhook, …

## Nice to have

- [ ] Redirect output streams #182 @chhsia0 
- [ ] Pipeline concurrency limit #1305 
- [ ] Custom Scheduler #3052 - Timebox work on investigation
- [ ] Tekton OCI bundle enabled by default @vdemeester 
- [ ] Proxy Support #3090 #2288 tektoncd/community#232 @piyush-garg 
- [ ] PipelineRun and TaskRun Status #3792

## To triage

- [ ] Provide a separate PipelineRun-volumeClaimTemplate, that can be mapped to multiple workspaces #3440 (in relation to workspaces @sbwsg)
- [ ] Task parallelism and Regional clusters - supported? #3563

## Use stories (to cover)

We should come with a bunch of user stories (from actual users) to highlight the requirements. 
- A standard go project pipeline (lint, build, test)
- A standard Java project pipeline (lint, package, test, publis, …) — maven and gradle versions
- A source-to-image project pipeline (build image, test, deployment)
- A source-to-image in knative project pipeline (build image, deployment, test, deployment)
- Tekton pipeline project pipeline (lint, build, test, e2e test against a cluster, …)
- A canary deployment pipeline
- A “matrix” build pipeline (build, test, … with some different env’ variables — using CustomResource)
- A Kubernetes pipeline execution engine for Kubeflow pipeline to leverage ML pipeline use cases (Python DSL to Tekton pipelineRuns, Data Transformation/processing, test, deploy and monitor k8s model training CR, model examination)
- *Add yours here*

See also [here](https://vincent.demeester.fr/articles/tekton-pipeline-without-pipeline-resources.html) :sweat_smile: 

/area epic
/area roadmap
/kind feature
/assign

/cc @tektoncd/core-maintainers

**Comment by jlpettersson** [comment]
I would like to see https://github.com/tektoncd/pipeline/issues/3440 in v1 - and deprecate the current place were `volumeClaimTemplate` is implemented. That would be a more intuitive API - easier to understand and easier to work with. I really regret the current design.

**Comment by bobcatfish** [comment]
I think that making some changes to the constraints the affinity assistant imposes before v1 would make a lot of sense - for example I really don't like it that (unless im understanding incorrectly) trying to use 2 PVCs with 1 Task right now will not be allowed (unless you disable the affinity assistant). Even if we keep that, I think it shouldn't be the default.

**Comment by jlpettersson** [comment]
@bobcatfish I opened https://github.com/tektoncd/pipeline/issues/3563 for discussion

**Comment by bobcatfish** [comment]
@vdemeester maybe we can triage https://github.com/tektoncd/pipeline/issues/3163 and potentially have it as part of our v1 roadmap?

**Comment by vdemeester** [comment]
> @vdemeester maybe we can triage #3163 and potentially have it as part of our v1 roadmap?

Except in " Migration path from v1beta1 to v1 " I don't see how it affects the `v1` API :thinking:.

**Comment by bobcatfish** [comment]
I think it's part of the migration path @vdemeester  - when we add v1, we'll have another API type to worry about having end to end tests for

**Comment by bobcatfish** [comment]
@vdemeester possible item to triage: have we discussed at all revisiting the structure of the `status` sections of TaskRun and PipelineRun? I don't think these were designed as carefully as the `spec` sections and there is some odd stuff in there. Or we can say it's good enough and go to v1 - but I think if we wanted to change it at all, we'd want to try to do it pre-v1

**Comment by vdemeester** [comment]
> @vdemeester possible item to triage: have we discussed at all revisiting the structure of the `status` sections of TaskRun and PipelineRun? I don't think these were designed as carefully as the `spec` sections and there is some odd stuff in there. Or we can say it's good enough and go to v1 - but I think if we wanted to change it at all, we'd want to try to do it pre-v1

We can definitely discuss that :)

**Comment by bobcatfish** [comment]
Another item to add to our list (from our governing board meeting):

* Fixing the security issues identified at https://security.lfx.linuxfoundation.org/#/a092M00001G3xhxQAB/foundation-details

**Comment by jerop** [comment]
@vdemeester we missed you in the API meeting on Monday where we discussed adding https://github.com/tektoncd/pipeline/issues/3548 to the V1 work here, what do you think?

**Comment by vdemeester** [comment]
> @vdemeester we missed you in the API meeting on Monday where we discussed adding #3792 to the V1 work here, what do you think?

We should definitely add it to the list of things to discuss and work on yes 😉

**Comment by sbwsg** [comment]
We might want to add the "phasing out HOME / workingDir" things as part of v1 work too:

https://github.com/tektoncd/pipeline/issues/2013
https://github.com/tektoncd/pipeline/issues/1836

**Comment by bobcatfish** [comment]
Another item to add to our list - I think @sbwsg 's comment touches on this - but we have a bunch of feature flags we can probably remove (i.e. set the behavior they guard as the default): https://github.com/tektoncd/pipeline/blob/master/docs/install.md#customizing-the-pipelines-controller-behavior (maybe these are just the creds related flags?)

**Comment by kobaji** [comment]
Hello @vdemeester and all thank you very much for publishing this issue.
Could you please tell me how I could reach the exact months or quarter of the Tekton pipeline's v1 API release?

I have checked the following documents but I could not have found the information.

- https://github.com/tektoncd/pipeline/blob/main/roadmap.md
- https://github.com/tektoncd/community/blob/main/roadmap.md

That information must be helpful for our team would contribute to Tekton.
Thank you.

**Comment by bobcatfish** [comment]
another thing to think about adding ... or removing that is XD: volumes + volume mounts (do these provide anything we need in addition to workspaces?) https://github.com/tektoncd/pipeline/issues/2058

**Comment by bobcatfish** [comment]
@kobaji I don't think we have any firm dates but are hoping for early 2022 (lemme know if you have different thoughts @vdemeester @afrittoli )

**Comment by vdemeester** [comment]
> another thing to think about adding ... or removing that is XD: volumes + volume mounts (do these provide anything we need in addition to workspaces?) #2058

Right, so on this, I am going to open an issue that is slightly related, on volume, workspace, configmap and secrets.

> @kobaji I don't think we have any firm dates but are hoping for early 2022 (lemme know if you have different thoughts @vdemeester @afrittoli )

Yeah that's more or less what I have in mind. And again, this is for a `v1` API, not necessarly a 1.0 release of tekton (that could happen before, or after).

**Comment by vdemeester** [comment]
https://github.com/tektoncd/pipeline/issues/4055 ^^

**Comment by kobaji** [comment]
> > @kobaji I don't think we have any firm dates but are hoping for early 2022 (lemme know if you have different thoughts @vdemeester @afrittoli )
> 
> Yeah that's more or less what I have in mind. And again, this is for a `v1` API, not necessarly a 1.0 release of tekton (that could happen before, or after).

Thank you @bobcatfish , @vdemeester for your kindness.
I will keep having a look regarding Tekton release.
Thank you again for your kind help.

**Comment by jerop** [comment]
consider if we need to tackle https://github.com/tektoncd/pipeline/issues/4399 before v1

**Comment by sbwsg** [comment]
Created https://github.com/tektoncd/pipeline/issues/4476 for discussion around `CluserTask`

**Comment by vdemeester** [comment]
@jerop how do we want to maintain this compared/with https://github.com/orgs/tektoncd/projects/10 and the V1 TEP ?

**Comment by lbernick** [comment]
I'd prefer using the project board since it makes it easier to add/remove issues, track their status, and add commentary about each one

**Comment by vdemeester** [comment]
@lbernick I tend to agree 😇

**Comment by jerop** [comment]
> @jerop how do we want to maintain this compared/with https://github.com/orgs/tektoncd/projects/10 and the V1 TEP ?

@vdemeester @lbernick agree with both of you that the project board is great for tracking items and the V1 TEP is useful for reaching alignment on what items are in scope -- thank you @vdemeester for scoping the items in this issue, it's been so useful and strongly influenced both the TEP and project board 🙏

**Comment by StevenACoffman** [comment]
BTW, I just thought to mention here that the various Tekton Roadmaps are all still listed as "2021 Roadmaps" such as https://github.com/tektoncd/pipeline/blob/main/roadmap.md and https://github.com/tektoncd/community/blob/main/roadmap.md#2021-roadmap (there are more).

**Comment by lbernick** [comment]
/close

using project board for tracking

**Comment by vdemeester** [comment]
> BTW, I just thought to mention here that the various Tekton Roadmaps are all still listed as "2021 Roadmaps" such as https://github.com/tektoncd/pipeline/blob/main/roadmap.md and https://github.com/tektoncd/community/blob/main/roadmap.md#2021-roadmap (there are more).

Yeah we need to *refine* those.

**Comment by jerop** [comment]
@StevenACoffman @vdemeester moved those roadmap items into a project view so that it's live: https://github.com/orgs/tektoncd/projects/16/views/15
