### ISSUE TITLE
Support Tekton OCI bundles without feature flag (i.e. promote to beta)

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#3661]
### Feature request

In https://github.com/tektoncd/pipeline/pull/3492 we put Tekton OCI bundles behind a feature flag to indicate that they are still "alpha" and to give us a chance to look into some issues @vdemeester discovered while using them.

This issue is to track the work to promote these bundles to a feature that you don't have to opt into.

TODO:
- [ ] Identify what we need to do to promote this feature
- [ ] Identify and solve performance issues
- [ ] Deal with complications around where you refer to Tasks at runtime (https://github.com/tektoncd/pipeline/issues/2298#issuecomment-725858538) - e.g. if you are making changes to a Task referenced by a Pipeline, how do you point that Pipeline to your in progress Task (currently you'd have to edit the Pipeline or publish the Task)

**Comment by vdemeester** [comment]
/lifecycle frozen
This is part of the roadmap 🙃

**Comment by lbernick** [comment]
Instead of promoting OCI bundles to beta, could we instead go ahead with promoting remote resolution to beta (#4710) and have people use the "bundle" resolver? as far as I can tell it provides the same functionality.

**Comment by vdemeester** [comment]
@lbernick yes, we need to decide which one to promote, but my feeling is that we should aim to promote remote resolution with the bundle resolver "built-in" probably, and deprecate the current way we refer bundles. It *is* gonna take some time though (to go from point A to point B), so we should decide this rather sooner.

**Comment by vdemeester** [comment]
Two things around this issue:
- I added this to the v1 board in order to make sure we go through it and we take a decision here.
- The current take is to put our efforts into the remote resolvers, see [here](https://github.com/tektoncd/pipeline/issues/4710), that would also support oci bundle, making this a "duplicate" way of refering to an OCI bundle.

I think we should make sure we mark the field (`taskref.bundle`) as deprecated as soon as possible (0.39 ?) so that we do not bring it in v1 and we rely on remote resolvers instead. Both are alpha today, so it shouldn't be a big deal to deprecate it (we could even remove it "abruptely" but because we use it in dogfooding as well as internally at Red Hat, I feel we should go the deprecation route).

/assign
(Assigning myself to prepare a pull-request deprecated the field)

**Comment by lbernick** [comment]
Proposed in https://github.com/tektoncd/community/pull/755

**Comment by lbernick** [comment]
Decision has been made to deprecate OCI bundles syntax, so I'm going to close this issue. @vdemeester feel free to reopen if there's anything else to track here
