### ISSUE TITLE
Hermekton Beta Tracking Issue

### ISSUE THREAD

**Issue by priyawadhwa** [tektoncd/pipeline#3965]
This is an overarching issue we can use to track the different things we'll need to do for hermekton beta:

- [ ] Figure out how we want to handle sidecar containers. We can either just document that they aren't supported or actually fail if hermetic execution mode is applied on a Task with sidecar containers
- [ ] Add sample working tasks & pipelines
- [ ] Make sure hermekton works if the user isn't running as root (more details in https://github.com/tektoncd/pipeline/pull/3956#issuecomment-844298352)
- [ ] Check if this will work across most major kernel versions
- [ ] Documentation on limitations/generally make sure docs are up to date
- [ ] Remove the alpha feature flag requirement for hermekton

Relevant Links:
TEP: https://github.com/tektoncd/community/blob/main/teps/0025-hermekton.md
Hermekton alpha PR: #3956

**Comment by imjasonh** [comment]
>  Figure out how we want to handle sidecar containers. We can either just document that they aren't supported or actually fail if hermetic execution mode is applied on a Task with sidecar containers

One option, at least for declared sidecars, would be to inject the entrypoint even if we don't otherwise use it to start the container. That wouldn't help with injected sidecars, but then we could just detect/block injected sidecars, instead of blocking all sidecars.

**Comment by priyawadhwa** [comment]
@imjasonh wouldn't we have to use the entrypointer to start the container as well? Right now hermekton basically takes the command the entrypointer would run and runs it in a namespace without network access, so I think we'd need the entrypointer to start sidecars as well for this to work-- 

https://github.com/tektoncd/pipeline/blob/145043aece13ed928425defc7ac2b36e30f5f631/cmd/entrypoint/runner.go#L63
