### ISSUE TITLE
Scope of `when` expressions 

### ISSUE THREAD

**Issue by jerop** [tektoncd/pipeline#4461]
As documented in the [deprecations](https://github.com/tektoncd/pipeline/blob/release-v0.29.x/docs/deprecations.md#deprecation-table), we are migrating the scope of `when` expressions.

| Feature Being Deprecated                                                                                                                                            | Deprecation Announcement                                             | [API Compatibility Policy](https://github.com/tektoncd/pipeline/tree/main/api_compatibility_policy.md) | Earliest Date or Release of Removal |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------ | ----------------------------------- |
| The `scope-when-expressions-to-task` flag will be flipped from "false" to "true"                               | [v0.27.0](https://github.com/tektoncd/pipeline/releases/tag/v0.27.0) | Beta                                                                                                   | February 10 2022                    |
| The `scope-when-expressions-to-task` flag will be removed                                                      | [v0.27.0](https://github.com/tektoncd/pipeline/releases/tag/v0.27.0) | Beta                                                                                                   | March 10 2022                       |

For more information, read [TEP-0059: Skipping Strategies](https://github.com/tektoncd/community/blob/main/teps/0059-skipping-strategies.md) and [related announcement](https://github.com/tektoncd/pipeline/discussions/4185). 

This is issue is tracking the work that we need to do here in the February and March releases. 

/kind feature
/assign

---

**Pull Requests**

- [x] https://github.com/tektoncd/pipeline/pull/4580
- [x] https://github.com/tektoncd/pipeline/pull/4584
- [ ] https://github.com/tektoncd/pipeline/pull/4715

**Comment by pritidesai** [comment]
Pipelines WG - Remove the flag in 0.35
