### ISSUE TITLE
Migrate PipelineRun Reconciler Tests to use YAMLParser

### ISSUE THREAD

**Issue by jerop** [tektoncd/pipeline#4610]
[`YAML` parsers](https://github.com/tektoncd/pipeline/blob/main/test/yaml.go) take a `YAML` in a string and returns respective deserialized objects including `Tasks`, `TaskRuns`, `Pipelines` and `PipelineRun` - thank you @imjasonh 🎉 

These parsers can help us simplify the many tests we have in [pipelinerun_test.go](https://github.com/tektoncd/pipeline/blob/302895b5a1ca45c02a85a9822201643c159fe02c/pkg/reconciler/pipelinerun/pipelinerun_test.go), and make it easier to add more reconciler tests so that we can safely make changes to the reconciler, such as refactoring and supporting [TEP-0090: Matrix](https://github.com/tektoncd/community/blob/main/teps/0090-matrix.md). 

Because the functions are long, we will use this issue to claim tests (to avoid duplicate work) and track progress. We'd appreciate any contributions to this migration 😸 

cc @pritidesai 

---

- [x] TestReconcile (@pritidesai) - https://github.com/tektoncd/pipeline/pull/4609
- [ ] TestReconcile_CustomTask
- [x] TestReconcile_PipelineSpecTaskSpec - https://github.com/tektoncd/pipeline/pull/4622
- [x] TestReconcile_InvalidPipelineRuns - https://github.com/tektoncd/pipeline/pull/4616
- [ ] ~~TestReconcile_InvalidPipelineRunNames~~ - no changes needed
- [ ] TestReconcileOnCompletedPipelineRun
- [ ] TestReconcileOnCancelledPipelineRunDeprecated
- [ ] TestReconcileOnCancelledPipelineRun
- [x] TestReconcileForCustomTaskWithPipelineTaskTimedOut - @anu-baskar is working on this!
- [ ] TestReconcileForCustomTaskWithPipelineRunTimedOut
- [ ] TestReconcileOnCancelledRunFinallyPipelineRun
- [ ] TestReconcileOnCancelledRunFinallyPipelineRunWithFinalTask
- [ ] TestReconcileOnCancelledRunFinallyPipelineRunWithRunningFinalTask
- [ ] TestReconcileOnCancelledRunFinallyPipelineRunWithFinalTaskAndRetries
- [ ] TestReconcileCancelledRunFinallyFailsTaskRunCancellation
- [ ] TestReconcileTaskResolutionError
- [ ] TestReconcileOnStoppedRunFinallyPipelineRun
- [ ] TestReconcileOnStoppedRunFinallyPipelineRunWithRunningTask
- [ ] TestReconcileOnStoppedPipelineRunWithCompletedTask
- [ ] TestReconcileOnPendingPipelineRun
- [ ] TestReconcileWithTimeout
- [ ] TestReconcileWithoutPVC
- [ ] TestReconcileCancelledFailsTaskRunCancellation
- [ ] TestReconcileCancelledPipelineRun
- [ ] TestReconcilePropagateLabels
- [ ] TestReconcilePropagateLabelsPending
- [ ] TestReconcilePropagateLabelsCancelled
- [ ] TestReconcileWithDifferentServiceAccounts
- [ ] TestReconcileCustomTasksWithDifferentServiceAccounts
- [ ] TestReconcileWithTimeoutAndRetry
- [ ] TestReconcilePropagateAnnotations
- [ ] TestGetTaskRunTimeout
- [ ] TestGetFinallyTaskRunTimeout
- [ ] TestReconcileAndPropagateCustomPipelineTaskRunSpec
- [ ] TestReconcileCustomTasksWithTaskRunSpec
- [ ] TestReconcileWithConditionChecks
- [ ] TestReconcileWithFailingConditionChecks
- [ ] TestReconcileWithWhenExpressionsWithParameters
- [ ] TestReconcileWithWhenExpressionsWithTaskResults
- [ ] TestReconcileWithWhenExpressionsScopedToTask
- [ ] TestReconcileWithWhenExpressionsScopedToTaskWitResultRefs
- [ ] TestReconcileWithAffinityAssistantStatefulSet
- [ ] TestReconcileWithVolumeClaimTemplateWorkspace
- [ ] TestReconcileWithVolumeClaimTemplateWorkspaceUsingSubPaths
- [ ] TestReconcileWithTaskResults
- [ ] TestReconcileWithTaskResultsEmbeddedNoneStarted
- [ ] TestReconcileWithPipelineResults
- [ ] Test_storePipelineSpec
- [ ] TestReconcileOutOfSyncPipelineRun
- [ ] TestUpdatePipelineRunStatusFromInformer
- [ ] TestUpdatePipelineRunStatusFromTaskRuns
- [ ] TestReconcilePipeline_FinalTasks
- [x] TestReconcile_CloudEvents - https://github.com/tektoncd/pipeline/pull/4619
- [ ] TestReconcilePipeline_TaskSpecMetadata
- [ ] TestReconciler_ReconcileKind_PipelineTaskContext
- [ ] TestReconcileWithTaskResultsInFinalTasks
- [ ] TestReconcile_RemotePipelineRef
- [ ] TestReconcile_OptionalWorkspacesOmitted
- [ ] TestReconcile_DependencyValidationsImmediatelyFailPipelineRun

---

In addition to the YAML Parser migration, move these three tests to `pipelinerunstate_test.go` - these three tests are mainly testing `func (state PipelineRunState) GetTaskRunsStatus`:
- [x] TestUpdateTaskRunsState - https://github.com/tektoncd/pipeline/pull/4632
- [x] TestUpdateRunsState - https://github.com/tektoncd/pipeline/pull/4632
- [x] TestUpdateTaskRunStateWithConditionChecks - https://github.com/tektoncd/pipeline/pull/4632

**Comment by jbpratt** [comment]
I don't think `TestReconcile_InvalidPipelineRunNames` has any updates required

**Comment by pritidesai** [comment]
> I don't think TestReconcile_InvalidPipelineRunNames has any updates required

Indeed, there are no changed needed in this test as part of this migration, thank you!

**Comment by vsinghai** [comment]
Wanted to bring to light that the `YAML Parser` cannot be used for tests in the `v1beta1` package due to a circular dependency within the `mustParse()` function.

**Comment by JeromeJu** [comment]
Noticed that most of the tests have been refactored thanks to #4749. 
I would love to help update the checkboxes and the issue if necessary.

**Comment by jerop** [comment]
> Noticed that most of the tests have been refactored thanks to #4749. I would love to help update the checkboxes if necessary.

yes please, thanks @JeromeJu

**Comment by JeromeJu** [comment]
Due to the authorization issue, I cannot edit on the issue. So instead leaving this comment to suggest closing 

While some of tests might be outdated, the ones that are left could be marked completed. 


***
Tests that might not require any updates.

- [x]  TestReconcileOnCancelledRunFinallyPipelineRun
- [x] TestReconcileOnCancelledRunFinallyPipelineRunWithFinalTaskAndRetries
- [x] TestReconcilePipeline_FinalTasks
- [x] TestGetTaskRunTimeout
- [x] TestGetFinallyTaskRunTimeout


Outdated:
- [ ] TestReconcileCancelledRunFinallyFailsTaskRunCancellation
- [ ] TestReconcileOnStoppedRunFinallyPipelineRun
- [ ] TestReconcileOnStoppedRunFinallyPipelineRunWithRunningTask
- [ ] TestReconcileOnStoppedPipelineRunWithCompletedTask
- [ ] TestReconcileCancelledPipelineRun
- [ ] TestReconcilePropagateLabelsCancelled
- [ ] TestReconcilePropagateLabelsPending
- [ ] TestReconcilePropagateAnnotations

**Comment by talife** [comment]
Here's an updated list I compiled.
For `TestUpdatePipelineRunStatusFromTaskRuns`, `mustParsePipelineRunTaskRunStatus` is inside `pipelinerun_updatestatus_test.go`. Should the parser be extended instead ?


* [x]  TestReconcile (@pritidesai) - [cleaning up a unit test to use YAMLParser #4609](https://github.com/tektoncd/pipeline/pull/4609)
* [x]  TestReconcile_CustomTask - [[TEP-0100] Prepare for testing of minimal status implementation](https://github.com/tektoncd/pipeline/pull/4734)
* [x]  TestReconcile_PipelineSpecTaskSpec - [refactor TestReconcile_PipelineSpecTaskSpec objects #4622](https://github.com/tektoncd/pipeline/pull/4622)
* [x]  TestReconcile_InvalidPipelineRuns - [cleaning up a unit test InvalidPipelineRuns to use YAML parser #4616](https://github.com/tektoncd/pipeline/pull/4616)
* [x]  ~TestReconcile_InvalidPipelineRunNames~ - no changes needed
* [x]  TestReconcileOnCompletedPipelineRun - [Update a number of PipelineRun reconciler tests with parsed YAML](https://github.com/tektoncd/pipeline/pull/4748)
* [x]  TestReconcileOnCancelledPipelineRunDeprecated - outdated
* [x]  TestReconcileOnCancelledPipelineRun - no changes needed
* [x]  TestReconcileForCustomTaskWithPipelineTaskTimedOut - @anu-baskar is working on this!
* [x]  TestReconcileForCustomTaskWithPipelineRunTimedOut - [Update a number of PipelineRun reconciler tests with parsed YAML](https://github.com/tektoncd/pipeline/pull/4748)
* [x]  TestReconcileOnCancelledRunFinallyPipelineRun - no changes needed
* [x]  TestReconcileOnCancelledRunFinallyPipelineRunWithFinalTask - [clean up reconcile unit test to use YAML parser](https://github.com/tektoncd/pipeline/pull/4637)
* [x]  TestReconcileOnCancelledRunFinallyPipelineRunWithRunningFinalTask - [Update a number of PipelineRun reconciler tests with parsed YAML](https://github.com/tektoncd/pipeline/pull/4748)
* [x]  TestReconcileOnCancelledRunFinallyPipelineRunWithFinalTaskAndRetries - no changes needed
* [x]  TestReconcileCancelledRunFinallyFailsTaskRunCancellation - outdated
* [x]  TestReconcileTaskResolutionError - [Migrate PipelineRun Reconciler__TestReconcileTaskResolutionError](https://github.com/tektoncd/pipeline/pull/5644)
* [x]  TestReconcileOnStoppedRunFinallyPipelineRun - outdated
* [x]  TestReconcileOnStoppedRunFinallyPipelineRunWithRunningTask - outdated
* [x]  TestReconcileOnStoppedPipelineRunWithCompletedTask - outdated
* [x]  TestReconcileOnPendingPipelineRun - [Switch (almost all of) the rest of pipelinerun_test.go to YAML parsing](https://github.com/tektoncd/pipeline/pull/4749)
* [x]  TestReconcileWithTimeout - outdated
* [x]  TestReconcileWithoutPVC - [Switch (almost all of) the rest of pipelinerun_test.go to YAML parsing](https://github.com/tektoncd/pipeline/pull/4749)
* [x]  TestReconcileCancelledFailsTaskRunCancellation - [Switch (almost all of) the rest of pipelinerun_test.go to YAML parsing](https://github.com/tektoncd/pipeline/pull/4749)
* [x]  TestReconcileCancelledPipelineRun - outdated
* [x]  TestReconcilePropagateLabels - oudated
* [x]  TestReconcilePropagateLabelsPending - outdated
* [x]  TestReconcilePropagateLabelsCancelled - outdated
* [x]  TestReconcileWithDifferentServiceAccounts - [Switch (almost all of) the rest of pipelinerun_test.go to YAML parsing](https://github.com/tektoncd/pipeline/pull/4749)
* [x]  TestReconcileCustomTasksWithDifferentServiceAccounts - [Switch (almost all of) the rest of pipelinerun_test.go to YAML parsing](https://github.com/tektoncd/pipeline/pull/4749)
* [x]  TestReconcileWithTimeoutAndRetry - [Switch (almost all of) the rest of pipelinerun_test.go to YAML parsing](https://github.com/tektoncd/pipeline/pull/4749)
* [x]  TestReconcilePropagateAnnotations - outdated
* [x]  TestGetTaskRunTimeout - outdated
* [x]  TestGetFinallyTaskRunTimeout - outdated
* [x]  TestReconcileAndPropagateCustomPipelineTaskRunSpec - outdated
* [x]  TestReconcileCustomTasksWithTaskRunSpec - [Switch (almost all of) the rest of pipelinerun_test.go to YAML parsing](https://github.com/tektoncd/pipeline/pull/4749)
* [x]  TestReconcileWithConditionChecks - outdated
* [x]  TestReconcileWithFailingConditionChecks - outdated
* [x]  TestReconcileWithWhenExpressionsWithParameters - outdated
* [x]  TestReconcileWithWhenExpressionsWithTaskResults - outdated
* [x]  TestReconcileWithWhenExpressionsScopedToTask - outdated
* [x]  TestReconcileWithWhenExpressionsScopedToTaskWitResultRefs - outdated
* [x]  TestReconcileWithAffinityAssistantStatefulSet - [Switch (almost all of) the rest of pipelinerun_test.go to YAML parsing](https://github.com/tektoncd/pipeline/pull/4749)
* [x]  TestReconcileWithVolumeClaimTemplateWorkspace - [Switch (almost all of) the rest of pipelinerun_test.go to YAML parsing](https://github.com/tektoncd/pipeline/pull/4749)
* [x]  TestReconcileWithVolumeClaimTemplateWorkspaceUsingSubPaths - [Switch (almost all of) the rest of pipelinerun_test.go to YAML parsing](https://github.com/tektoncd/pipeline/pull/4749)
* [x]  TestReconcileWithTaskResults - [Update a number of PipelineRun reconciler tests with parsed YAML](https://github.com/tektoncd/pipeline/pull/4748)
* [x]  TestReconcileWithTaskResultsEmbeddedNoneStarted - [Update a number of PipelineRun reconciler tests with parsed YAML](https://github.com/tektoncd/pipeline/pull/4748)
* [x]  TestReconcileWithPipelineResults - [Add support for finally task results in pipeline results](https://github.com/tektoncd/pipeline/pull/5170)
* [x]  Test_storePipelineSpec - outdated
* [x]  TestReconcileOutOfSyncPipelineRun - [Switch (almost all of) the rest of pipelinerun_test.go to YAML parsing](https://github.com/tektoncd/pipeline/pull/4749)
* [x]  TestUpdatePipelineRunStatusFromInformer - [Switch (almost all of) the rest of pipelinerun_test.go to YAML parsing](https://github.com/tektoncd/pipeline/pull/4749)
* [ ]  TestUpdatePipelineRunStatusFromTaskRuns
* [x]  TestReconcilePipeline_FinalTasks - no changes needed
* [x]  TestReconcile_CloudEvents - [clean up TestReconcile_CloudEvents YAML parsing #4619](https://github.com/tektoncd/pipeline/pull/4619)
* [x]  TestReconcilePipeline_TaskSpecMetadata - [refactor reconcile pipeline TaskSpecMetadata test](https://github.com/tektoncd/pipeline/pull/4693)
* [x]  TestReconciler_ReconcileKind_PipelineTaskContext - [Switch (almost all of) the rest of pipelinerun_test.go to YAML parsing](https://github.com/tektoncd/pipeline/pull/4749)
* [x]  TestReconcileWithTaskResultsInFinalTasks - [Update a number of PipelineRun reconciler tests with parsed YAML](https://github.com/tektoncd/pipeline/pull/4748)
* [x]  TestReconcile_RemotePipelineRef - [Switch (almost all of) the rest of pipelinerun_test.go to YAML parsing](https://github.com/tektoncd/pipeline/pull/4749)
* [x]  TestReconcile_OptionalWorkspacesOmitted - [Switch (almost all of) the rest of pipelinerun_test.go to YAML parsing](https://github.com/tektoncd/pipeline/pull/4749)
* [x]  TestReconcile_DependencyValidationsImmediatelyFailPipelineRun - [Switch (almost all of) the rest of pipelinerun_test.go to YAML parsing](https://github.com/tektoncd/pipeline/pull/4749)

In addition to the YAML Parser migration, move these three tests to `pipelinerunstate_test.go` - these three tests are mainly testing `func (state PipelineRunState) GetTaskRunsStatus`:

* [x]  TestUpdateTaskRunsState - [cleanup - refactor taskRunStatus and runStatus unit tests #4632](https://github.com/tektoncd/pipeline/pull/4632)
* [x]  TestUpdateRunsState - [cleanup - refactor taskRunStatus and runStatus unit tests #4632](https://github.com/tektoncd/pipeline/pull/4632)
* [x]  TestUpdateTaskRunStateWithConditionChecks - [cleanup - refactor taskRunStatus and runStatus unit tests #4632](https://github.com/tektoncd/pipeline/pull/4632)

**Comment by jerop** [comment]
Migration was completed, thank you for the contributions!
