### ISSUE TITLE
TEP-0100: `PipelineRun` Status Migration

### ISSUE THREAD

**Issue by jerop** [tektoncd/pipeline#4954]
[TEP-0100: Embedded TaskRuns and Runs Status in PipelineRuns][tep-0100] proposed changes to `PipelineRun` status to reduce the amount of information stored about the status of `TaskRuns` and `Runs` to improve performance, reduce memory bloat and improve extensibility. 

This feature was released in [v0.35.0][35] gated behind the `embedded-status` feature flag, and this issue tracks the migration and removal of that feature flag.

- [x] [v0.35.0][35]: `embedded-status` flag defaults to `full`
- [x] [v0.44.0][44]: `embedded-status` flag defaults to `minimal`
- [ ] [v0.45.0][45]: `embedded-status` flag is removed

[tep-0100]: https://github.com/tektoncd/community/blob/main/teps/0100-embedded-taskruns-and-runs-status-in-pipelineruns.md
[35]: https://github.com/tektoncd/pipeline/releases/tag/v0.35.0
[44]: https://github.com/tektoncd/pipeline/releases/tag/v0.44.0
[45]: https://github.com/tektoncd/pipeline/releases/tag/v0.45.0

**Comment by jerop** [comment]
06.24 update: we are dogfooding the minimal status in the alpha integration tests
- https://github.com/tektoncd/pipeline/pull/5032
- https://github.com/tektoncd/plumbing/pull/1096

**Comment by JeromeJu** [comment]
Planning on how to remove the embedded-status feature flag entirely:
- Start from the pipelinerun reconciler? or the test cases?
- Finally cleanup the docs

**Comment by afrittoli** [comment]
One part of this will be addressed in v0.44, but I think we will only close in v0.45, so perhaps we should move this to that milestone?

**Comment by JeromeJu** [comment]
> One part of this will be addressed in v0.44, but I think we will only close in v0.45, so perhaps we should move this to that milestone?

The TEP100 and this issue shall close only in v0.45, sounds good to me. Thanks @afrittoli

**Comment by JeromeJu** [comment]
- [ ] [v0.45.0](https://github.com/tektoncd/pipeline/releases/tag/v0.45.0): embedded-status flag is removed

   - For the changes in v0.45, the test cases with FullEmbeddedStatus shall be removed along with the flag value.

**Comment by JeromeJu** [comment]
Earlier I drafted up https://github.com/tektoncd/pipeline/pull/6049 only to figure out which would be the better practice for implementing the removal of the `embedded-status` flag for v0.45. And for the purpose of code hygiene and easy rollback for review, I would like to propose separating them into the following:

- [ ] one pull request for refactoring/ removing all the test cases for pipelineRunStatus with `full` and `both` embedded status
- [ ] one pull request for the integration test cases for removing the requireAnyGate of `full` or `both` embedded status
- [ ] one pull request for changing the reconciler logics and removing the flag
- [ ] one pull request for changing the `embedded-status` in the plumbing repo for prow setup

Please let me know if this sounds good cc @abayer @jerop @lbernick. Thanks!

**Comment by lbernick** [comment]
https://github.com/tektoncd/community/pull/931 is not merged yet, but in it, I added the guidance "Tests and documentation (where applicable) should always be part of the same pull request when introducing a change". To expand on this a bit in this context: If you remove tests first, we now have untested functionality (different values of the feature flag) in our code base. We wouldn't allow someone to introduce functionality without tests, so we should also not allow tests to be removed before the functionality is. The same is true for documentation. In terms of "easy rollback": if there was an issue with removing the feature flag and we wanted to revert the commit removing the flag, we would also want to revert removal of the tests. Therefore, I'd put this all in the same PR.

Changing our prow cluster configuration is a separate repo, so that can happen completely independently.

**Comment by JeromeJu** [comment]
> [tektoncd/community#931](https://github.com/tektoncd/community/pull/931) is not merged yet, but in it, I added the guidance "Tests and documentation (where applicable) should always be part of the same pull request when introducing a change". To expand on this a bit in this context: If you remove tests first, we now have untested functionality (different values of the feature flag) in our code base. We wouldn't allow someone to introduce functionality without tests, so we should also not allow tests to be removed before the functionality is. The same is true for documentation. In terms of "easy rollback": if there was an issue with removing the feature flag and we wanted to revert the commit removing the flag, we would also want to revert removal of the tests. Therefore, I'd put this all in the same PR.
> 
> Changing our prow cluster configuration is a separate repo, so that can happen completely independently.

Makes sense! I will stick to the same PR then.

**Comment by JeromeJu** [comment]
Opened - https://github.com/tektoncd/pipeline/issues/6090 for cleanup after the removal of `embedded-status` feature flag in v0.45.
