### ISSUE TITLE
TEP-0107: Propagated `Parameters` Migration

### ISSUE THREAD

**Issue by jerop** [tektoncd/pipeline#4955]
[TEP-0107: Propagating Parameters][tep-0107] proposed propagating `Parameters` in embedded specifications without mutations. This feature was released in [v0.36.0][36] gated behind the `alpha` feature flag. 

This issue tracks the removal of that feature flag and promotion to Beta - targeting release [v0.40.0][40].

- [x] https://github.com/tektoncd/pipeline/issues/5141
- [x] https://github.com/tektoncd/pipeline/issues/5140
- [x] https://github.com/tektoncd/pipeline/issues/5588
- [x] https://github.com/tektoncd/pipeline/pull/5540

[tep-0107]: https://github.com/tektoncd/community/blob/main/teps/0107-propagating-parameters.md
[36]: https://github.com/tektoncd/pipeline/releases/tag/v0.36.0
[40]: https://github.com/tektoncd/pipeline/releases/tag/v0.40.0

**Comment by jerop** [comment]
Completed in https://github.com/tektoncd/pipeline/pull/5540 - Thank you @chitrangpatel!
