### ISSUE TITLE
Release v1 versions of Task, TaskRun, Pipeline, and PipelineRun CRDs

### ISSUE THREAD

**Issue by lbernick** [tektoncd/pipeline#5541]
This issue tracks the release of v1 api versions for Task, TaskRun, Pipeline, and PipelineRun.

Before doing this, we would like to wait for remote resolution beta (https://github.com/tektoncd/pipeline/issues/4710), since we want to provide an alternative to taskref.bundle and pipelineref.bundle.

It would be nice to wait for custom tasks beta (https://github.com/tektoncd/pipeline/issues/4313) so we can release v1 versions of these CRDs along with custom task beta, but there's still more work to do there and I'm not sure this should be a blocker.

Steps:
1. Create examples tests for v1 versions of our CRDs (probably just copy pasting existing examples tests, swapping api versions, and removing any that aren't relevant for v1 such as those that test pipelineresources). This will probably require step 2 but it would be nice if there's a way to do it first. It will probably be easiest to do all the CRDs at once, but it's not necessary to do so.
2. Update CRDs to serve v1 versions. At this point, we're "committing" to the structure of the v1 api-- no more changes.
3. Update CRDs to use v1 as the stored version, and in the same PR, update the reconcilers to reconcile the v1 versions of the CRDs. Again, we don't have to do all the CRDs at once here, but we might find it easier to do so. One catch is that we must deserialize PipelineResources from annotations in v1 CRDs if they are present. (They may have been created by conversion from v1beta1 CRDs referencing PipelineResources.) Failing to support PipelineResources in this way would be violating our compatibility policy by not supporting a v1beta1 feature for 9 months following the v1 release. After completing step 3, we'll be able to add new features in v1 and should stop making any changes to v1beta1.

**Comment by lbernick** [comment]
Discussed in today's api wg: folks seem to be OK with going forward with this plan without blocking on custom tasks beta but would like to block on remote resolution beta. We should review our plan for supporting deprecated fields (#4546) before swapping our stored versions over to v1.

**Comment by JeromeJu** [comment]
Would like to confirm the understanding on the part iii.

Basically what is needed here is changing most `v1beta1` to `v1` in reconcilers and regarding directories. While for the deprecated fields, I am referring to the previous [v1alpha1 to v1beta1 changes](https://github.com/tektoncd/pipeline/pull/2577/files#diff-6e67e9c647bbe2a08807ff5ccbdd7dc9036df373e56b9774d3996f92ab7ceaba) and in the example of deprecated resources for taskRun, I would need to check `tr.ObjectMeta.Annotations` contains `resources` and if so reusing the v1beta1 reconciling codes while marking it as deprecated in comments?

**Comment by lbernick** [comment]
Yes, that sounds right to me!

**Comment by JeromeJu** [comment]
Now that the V1 CRD has been released in v0.43 at #5579, the following tasks will be done according to part iii:
- [ ] Swap Task to storage version
- [ ] Swap Pipeline to storage version
- [ ] Swap TaskRun to storage version
- [ ] Swap PipelineRun to storage version

**Comment by JeromeJu** [comment]
Deprecated features that needs to be handled as part of the storage version migration:

- [ ] PipelineResources  (can be removed at the moment)
- [ ] CloudEvents           (July 13)
- [ ] [ClusterTask](https://github.com/tektoncd/pipeline/issues/4476)    (July 13)
- [ ] [PipelineRun.Timeout](https://github.com/tektoncd/community/blob/main/teps/0046-finallytask-execution-post-timeout.md) (Feb 25)
- [ ]

**Comment by JeromeJu** [comment]
What needs to be done before swapping v1 storage:

- [ ] Refine conversion test: as described before for preventing issues ie. https://github.com/tektoncd/pipeline/issues/5964
- [ ] https://github.com/tektoncd/pipeline/issues/5979

**Comment by JeromeJu** [comment]
> I don't think addressing issues like #5964 is a blocker for swapping the storage version to v1.
My understanding is instead of addressing issues like #5964 , the round-trip conversion test is to prevent such issue from happening if that makes sense?

> It seems like #5979 and #5967 are the only blockers?
Yes, I agree. But I think #5979 is going to be handled within the same PR of the storage swap since I could not figure out a way to separately isolate the TaskObject interface.

**Comment by lbernick** [comment]
Would you mind updating https://github.com/tektoncd/pipeline/issues/5979 with the details of what you tried?

**Comment by JeromeJu** [comment]
Aligned in WG @4 April that we are going to delay to v0.48, which is after the earliest LTS v0.47 to minimize impacts on LTS users while we are going to merge v1 storage swap soon as possible in early v0.48 to get enough window for fixing for v0.48.

**Comment by JeromeJu** [comment]
Current blockers/ questions:
- [ ] https://github.com/tektoncd/pipeline/pull/6496
- [ ] https://github.com/tektoncd/pipeline/pull/6497

**Comment by JeromeJu** [comment]
This is to update the current blockers:

- [ ] [Handle Loss of Deprecated Container Fields in v1 for Step LivenessProbes and etc.](https://github.com/tektoncd/pipeline/issues/6575)
- [ ] We need to update the default type assignment for empty map instantiated in conversions: (for context, taskResults.properties are created as an empty map in conversions)
  - [ ] [Guard Empty ParamSpec Properties Type Assign](https://github.com/tektoncd/pipeline/pull/6578)
  - [ ] [Guard Empty TaskResult Properties Type Assign](https://github.com/tektoncd/pipeline/pull/6570)
- [ ] [Decoupling API versioning and Feature versioning for features turned on by default #6592](https://github.com/tektoncd/pipeline/issues/6592)
  -[ ] [Resolver to Stable #6579](https://github.com/tektoncd/pipeline/issues/6579)

**Comment by dibyom** [comment]
@lbernick and I did some investigating around the test failures summarized in #6608 (tl;dr unit tests pass, some integration tests fail due to the issue in #6592)

### TODOs

- [ ] Fix Unit tests for #6608 
- [ ] Fix Integration test for #6608 (likely blocked on #6592 and #6575)
- [ ] Find a way forward for #6592 
- [ ] Fix #6575 
- [ ] Other issues:
    - [ ]   API versioning for remotely fetched tasks - what happens if a resolvers returns v1 tasks/pipelines but the reconciler uses v1beta1 (or vice-versa)

**Comment by pritidesai** [comment]
Pipelines WG - this is at risk, blocked by an issue #6616

**Comment by chuangw6** [comment]
> Pipelines WG - this is at risk, blocked by an issue #6616

Seems like it's less possible to include this in v0.48. Should we move it to next release?
