### ISSUE TITLE
TEP-0127: Larger Results via Sidecar Logs

### ISSUE THREAD

**Issue by jerop** [tektoncd/pipeline#5851]
This issue tracks the implementation of [TEP-0127: Larger Results via Sidecar Logs](https://github.com/tektoncd/community/blob/main/teps/0127-larger-results-via-sidecar-logs.md):

- [x] https://github.com/tektoncd/pipeline/pull/5828
- [x] https://github.com/tektoncd/pipeline/pull/5838
- [x] https://github.com/tektoncd/pipeline/pull/5843
- [x] https://github.com/tektoncd/pipeline/pull/5834
- [x] https://github.com/tektoncd/pipeline/pull/5840 
- [x] https://github.com/tektoncd/pipeline/pull/5695
- [x] https://github.com/tektoncd/pipeline/pull/5877
