### ISSUE TITLE
TEP-0127: Larger Results via Sidecar Logs [Feedback]

### ISSUE THREAD

**Issue by jerop** [tektoncd/pipeline#6133]
In [TEP-0127](https://github.com/tektoncd/community/blob/main/teps/0127-larger-results-via-sidecar-logs.md), we proposed  Larger Results via Sidecar Logs. This feature was added in release [v0.43](https://github.com/tektoncd/pipeline/releases/tag/v0.43.0) as an alpha feature that's guarded behind the `results-from` feature flag. For further details, see the [documentation](https://github.com/tektoncd/pipeline/blob/main/docs/tasks.md#larger-results-using-sidecar-logs).

This is an issue to gather feedback from users who have tried out the the feature, so that we can figure out a way forward.

**Comment by pritidesai** [comment]
The larger results via sidecar logs is a huge improvement to address 4K termination message size limitation. I am evaluating using this feature in our service. This feature does not help accomplish artifacts use case but it is a step forward while working with a [reasonable](https://github.com/tektoncd/pipeline/issues/4282#issuecomment-936318162) size of task results.

This is a live list of to-dos for making sure this feature can be promoted to `beta`:

- [ ] Fix formatting issues in [docs](https://github.com/tektoncd/pipeline/blob/main/docs/tasks.md#larger-results-using-sidecar-logs) and add a complete set of instructions on how to enable larger results using sidecar logs. The additional-configs has the set of instructions, either we move them under `docs/tasks.md` or provide a reference to `additional-configs` from `docs/tasks.md`. 
- [ ] Add multiple tasks producing multiple task results in an example pipeline.
- [ ] Add an example pipeline which has a task producing large results + `onError` is set to `continue`. This test is necessary to check the sidecar `sidecar-tekton-log-results` supports non-zero exit code of any container.
- [ ] Add `e2e` test to validate the task results are produced with a failed task.
- [ ] Add an example pipeline to produce task results of all supported types including `array` and `object`.

**Comment by jerop** [comment]
@pritidesai thank you for the feedback, will prioritize making the improvements that you've suggested

**Comment by jerop** [comment]
> @JeromeJu @pritidesai mentioned that larger results tests are gated by both the alpha flag as well as a dedicated feature flag. Can we use just one of them or is this intentional?

It is no longer gated behind the alpha feature flag https://github.com/tektoncd/pipeline/pull/6939

**Comment by chitrangpatel** [comment]
https://github.com/tektoncd/pipeline/pull/8041 adds the tests
