### ISSUE TITLE
TEP-0091: Trusted Resources TODO work before Beta

### ISSUE THREAD

**Issue by Yongxuanzhang** [tektoncd/pipeline#6356]
This issue is tracking relevant features before we could promo trusted resources to Beta. 
If you have any other requirements, feel free to leave comments on this issue. 

/kind feature 

Background: In this PR https://github.com/tektoncd/community/pull/949, we proposed several features for trusted resources. Those could help the project to meet more users need. 

Checklist:
- [x]  Feature flag change from `resources-verificaiton-mode` to `trusted-resources-verification-no-match-policy`.
- https://github.com/tektoncd/pipeline/pull/6324 
- [x]  Add condition to reflect verification failure/success. https://github.com/tektoncd/pipeline/issues/6665
- [x]  Add a new field "mode" with "warn" and "enforce" as available values.
1. Add mode field in api: https://github.com/tektoncd/pipeline/pull/6328 
2. Use mode in reconciler, if mode if empty, it should be treated as `enforce`: https://github.com/tektoncd/pipeline/pull/6406
- [x]  Support v1 Tasks&Pipelines: https://github.com/tektoncd/pipeline/issues/6729
1. support in remote resolution: https://github.com/tektoncd/pipeline/pull/6254
2. support in trusted resources in [task](https://github.com/tektoncd/pipeline/blob/add97eae68d2f1ca131163645f0ca37913090494/pkg/reconciler/taskrun/resources/taskref.go#L190) and [pipeline](https://github.com/tektoncd/pipeline/blob/add97eae68d2f1ca131163645f0ca37913090494/pkg/reconciler/pipelinerun/resources/pipelineref.go#L174)

- [ ] Support local tasks and pipelines: https://github.com/tektoncd/pipeline/issues/6666
- [ ] Clean up code (rename "expected-want" in tests, clean error logs)

**Comment by jerop** [comment]
There's no open pr getting trusted resources to beta, so moving this item to the next milestone

@Yongxuanzhang please let me know if I missed something

**Comment by Yongxuanzhang** [comment]
> There's no open pr getting trusted resources to beta, so moving this item to the next milestone
> 
> @Yongxuanzhang please let me know if I missed something

Thanks!

**Comment by pritidesai** [comment]
Pipelines WG - @Yongxuanzhang breaking this into smaller PRs. @Yongxuanzhang to move to the next milestone if we don't make it.

**Comment by Yongxuanzhang** [comment]
The left items all have their dedicated issues:

1. [TEP-0091] Support local resources verification  #6666
2. Clean up code: https://github.com/tektoncd/pipeline/issues/5820

Close this one since all feature PRs are merged
