### ISSUE TITLE
Tracking bug for TEP-0089

### ISSUE THREAD

**Issue by jagathprakash** [tektoncd/pipeline#6597]
This is a tracking bug for the implementation of [TEP-0089](https://github.com/tektoncd/community/blob/main/teps/0089-nonfalsifiable-provenance-support.md).

TEP-0089 is a proposal to enforce non-falsifiable provenance using SPIRE.

The PRs created to implement this issue are

- [X] [PR-5039](https://github.com/tektoncd/pipeline/pull/5039) [TEP-0089] - Spire Package
- [X] [PR-5647](https://github.com/tektoncd/pipeline/pull/5647) [TEP-0089] Apis to handle SPIRE signing and verification.
- [X] [PR-5676](https://github.com/tektoncd/pipeline/pull/5676) [TEP-0089] Modify entrypoint to sign the results.
- [X] [PR-5902](https://github.com/tektoncd/pipeline/pull/5902) [TEP-0089] Add a config map to support SPIRE initialization. 
- [X] [PR-6524](https://github.com/tektoncd/pipeline/pull/6524) [TEP-0089] SPIRE for non-falsifiable provenance - IsSpireEnabled
- [X] [PR-6527](https://github.com/tektoncd/pipeline/pull/6527) TEP-0089: Refactor setting of "enforce-nonfalsifiability" feature flag
- [ ] [PR-6539](https://github.com/tektoncd/pipeline/pull/6539) [TEP-0089] Add CSI volumes to the Pods which provide the SPIRE workload API
- [ ] [PR-6553](https://github.com/tektoncd/pipeline/pull/6553) [TEP-0089] SPIRE for non-falsifiable provenance. Setup the test environment

**Comment by pritidesai** [comment]
Lets clear the milestone for now, we can bring it back if someone volunteers or we find someone to work on this. We do not have any owner at this time.

**Comment by afrittoli** [comment]
This is not completed though, there are bits missing.
I asked Claude to check the status of the implementation and to compare it with an implementation based on k8s  OIDC / Service Account Tokens, and he produced this [plan](https://gist.github.com/afrittoli/97798b9b32b736a82f192378eac81ea5)  for me.
> [!CAUTION] 
> The [plan](https://gist.github.com/afrittoli/97798b9b32b736a82f192378eac81ea5) is raw from Claude, I've not had bandwidth to review it myself, but it may be useful to anyone interested in picking this up.
