### ISSUE TITLE
Epic: Upgrade test improvements

### ISSUE THREAD

**Issue by lbernick** [tektoncd/pipeline#6870]
Bug fixes
- [x] https://github.com/tektoncd/pipeline/issues/5193
- [x] https://github.com/tektoncd/pipeline/issues/5689
- [ ] https://github.com/tektoncd/pipeline/issues/6868
- [ ] https://github.com/tektoncd/pipeline/issues/6869

Possible improvements
- [ ] https://github.com/tektoncd/pipeline/issues/5782
- [ ] "downgrade" testing: https://github.com/tektoncd/pipeline/issues/6841
- [ ] https://github.com/tektoncd/pipeline/issues/6709
- [ ] https://github.com/tektoncd/pipeline/issues/6024
