### ISSUE TITLE
TEP-152 Tekton Conformance Verification

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/pipeline#7828]
### Context

With the release of [v1 Tekton conformance API spec](https://github.com/tektoncd/pipeline/blob/main/docs/api-spec.md), the Tekton community can now offer Tekton conformance verification. The conformance test suite will be the crucial prerequisite for vendors to claim conformance for their service.

### Work PLAN
Refine existing V1 Tekton Conformance API Spec
- [ ] [Conformance V1: make SideCarState Required](https://github.com/tektoncd/pipeline/pull/7827)
Implementation of the OSS Tekton Conformance verification test suite.
- [ ] [Initiate Conformance Test Suite](https://github.com/tektoncd/pipeline/pull/7826)
Documentation of the OSS practice for claiming conformance.
- [ ] Setup WG for conformance-related dicussions.

**Comment by chitrangpatel** [comment]
@JeromeJu is this completed?
